### ISSUE TITLE
Support multiple datasources

### ISSUE THREAD

**Issue by grobie** [percona/grafana-app#2]
Great work! We have tens of Prometheus servers though with lot's of names and not a single one called `Prometheus`. Grafana >=3.0.3 supports templated datasources which would help a lot here.

**Comment by roman-vynar** [comment]
Thanks Tobias, I will look into it.

**Comment by roman-vynar** [comment]
@grobie a side question, do you employ `alias` label to name hosts or `instance` works for you?

I am thinking to change from using `alias` to `instance` and want to consider whether this is a really good idea. You know not saving ip:port into `instance` prevents poluting time-series and breaking graphs when the same host (currently named `alias`) changes the ip or exposing port.

**Comment by grobie** [comment]
Please use `instance`. If people have issues about non-descriptive `instance` labels, they should relabel it. Here is a blog post for that http://www.robustperception.io/controlling-the-instance-label/

**Comment by roman-vynar** [comment]
Thanks, will do that.

**Comment by Oneiroi** [comment]
Apologies, this repo is currently deprecated users should refer to https://github.com/percona/grafana-dashboards/ at this time, closing this issue; thank you.
