### ISSUE TITLE
Migrate to standalone dashboards

### ISSUE THREAD

**Issue by torkelo** [percona/grafana-app#3]
Hi, 

We have introduced dashboard sharing on Grafana.net. 

Any change this app could be migrated to standalone dashboards, meaning upload a dashboard for each dashboard in this app. 

https://grafana.net/dashboards

**Comment by roman-vynar** [comment]
@torkelo yeah, we can do.

One thing - is it possible to get this super-easy fix into the next Grafana?
```
sed -i 's/expr=\(.\)\.replace(\(.\)\.expr,\(.\)\.scopedVars\(.*\)var \(.\)=\(.\)\.interval/expr=\1.replace(\2.expr,\3.scopedVars\4var \5=\1.replace(\6.interval, \3.scopedVars)/' /usr/share/grafana/public/app/plugins/datasource/prometheus/datasource.js
```

It lasts from Grafana 2.6.x and aiming to allow using a template variable in the "Interval" field of Prometheus query editor. We have had already discussions on that but it turned into rewritting Prometheus Query Editor and never went through. It is important to have this simple fix so the graphs are correct in numbers and better zoomable when using `rate()` function (majority of the graphs).

Is this doable? No harm to any other features, behaviour etc. you know.

**Comment by torkelo** [comment]
PR?

**Comment by roman-vynar** [comment]
@torkelo https://github.com/grafana/grafana/pull/5839

**Comment by Oneiroi** [comment]
Apologies, this repo is currently deprecated users should refer to https://github.com/percona/grafana-dashboards/ at this time, closing this issue; thank you.
