### ISSUE TITLE
count_scalar deprecated

### ISSUE THREAD

**Issue by asmsoft** [percona/grafana-app#6]
Prometheus doesn't support count_scalar anymore.
https://groups.google.com/forum/#!topic/prometheus-users/P5CZWArvMb0
count_scalar(...) -> scalar(count(...))

**Comment by Oneiroi** [comment]
Apologies, this repo is currently deprecated users should refer to https://github.com/percona/grafana-dashboards/ at this time, closing this issue; thank you.
